#!/usr/bin/env bash


sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html > /dev/null
sudo service nginx restart

#!/usr/bin/env bash

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo sh -c 'echo "Hello World!" > /usr/share/nginx/html/index.html'
sudo service nginx restart



